language: scala
scala:
  - 2.12.11
  - 2.13.2
sudo: false
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
script:
  - sbt ++$TRAVIS_SCALA_VERSION autowireJVM/test autowireJS/test
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
