os: linux
language: scala
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - script: "./mill -j $(nproc) __.js.__.test"
    jdk: openjdk11

  - script: "./mill -j $(nproc) __.jvm.__.test"
    jdk: openjdk11

  - script: "./mill -j $(nproc) __.native.__.test"
    jdk: openjdk8
    before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x

  - stage: release
    script:
      - echo "$PGP_SECRET" | base64 --decode | gpg --import
      - ./mill -j $(nproc) __.jvm[__].publish --sonatypeCreds "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" --release true --gpgPassphrase "$PGP_PASSPHRASE"

  - stage: release
    script:
      - echo "$PGP_SECRET" | base64 --decode | gpg --import
      - ./mill -j $(nproc) __.js[__].publish --sonatypeCreds "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" --release true --gpgPassphrase "$PGP_PASSPHRASE"

  - stage: release
    script:
      - echo "$PGP_SECRET" | base64 --decode | gpg --import
      - ./mill -j $(nproc) __.native[__].publish --sonatypeCreds "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" --release true --gpgPassphrase "$PGP_PASSPHRASE"
