os: linux
dist: bionic
language: scala
stages:
  - name: test
  - name: release
    if: branch = master AND type = push AND tag IS present
jobs:
  include:
  - script: "./mill -j $(nproc) __.js.__.test"
    jdk: openjdk11

  - script: "./mill -j $(nproc) __.jvm.__.test"
    jdk: openjdk11

  - script: "./mill -j $(nproc) __.native.__.test"
    jdk: openjdk8

  - stage: release
    script:
      - echo $GPG_PRIVATE_KEY_B64 | base64 --decode > gpg_key
      - gpg --import gpg_key 
      - rm gpg_key
      - ./mill mill.scalalib.PublishModule/publishAll \
        --sonatypeCreds lihaoyi:$SONATYPE_PASSWORD \
        --gpgArgs --passphrase=$GPG_PASSWORD,--batch,--yes,-a,-b \
        --publishArtifacts __.publishArtifacts \
        --readTimeout 600000 \
        --release true \
        --signed true
